### ISSUE TITLE
[feature-request] ability to delay deletion

### ISSUE THREAD

**Issue by ahcarpenter** [SvanBoxel/delete-merged-branch#46]
Would be awesome to be able to delay deletion of a branch.

Use case: Sometimes I’m working on a feature branch and it gets approved and merged. Later, a bug gets noticed and I go to pull the latest copy of that branch as it was right before merge (to handle cases, for instance, if there had been edits before approval on remote only, or to avoid pulling from master where there may potentially be new commits), though this typically would only be within a set period of time (ie. maybe typically within the first 7 days after initial merge)

Would be nice to account for scenarios like this and be able to access the branch without having to restore first, but still have it auto deleted after a set period of time

Also, thanks a ton as-is for this @SvanBoxel def a fan!

Also, would most definitely be more than happy to help and can most def queue up circling back around here!

**Comment by SvanBoxel** [comment]
Hello @ahcarpenter! Great feature request and realistic use case.

The current architecture doesn't support a lot of [persistence](https://probot.github.io/docs/persistence/). Whatever is in memory will be removed whenever we deploy a new version of this app or restart the server. Therefore implementing this functionality in the current architecture isn't realistic because it will be too unreliable.

**Comment by SvanBoxel** [comment]
Closing this issue because of https://github.com/SvanBoxel/delete-merged-branch/issues/46#issuecomment-443000791
